version: "3"

services:
  db:
  server:
      build: ./server
      environment:
        - PORT=5000
        - NODE_ENV=production
      ports:
        - 5000:5000
      restart: always

  client:
    build: ./client
    environment:
      - REACT_APP_PORT=3000
      - ENV=production
    ports:
      - 3000:3000
    links:
      - server
    restart: always
