version: "3"

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always      
  server:
      build: ./server
      environment:
        - MONGODB_URI=mongodb://db:27017/ctrlv
        - PORT=5000
        - NODE_ENV=dev-docker
      ports:
        - 5000:5000
      volumes:
        # Map client src to server src to hot reload
        - ./server/src:/app/server/src
      links:
        - db
      command: npm run start-watch
      restart: always

  client:
    build: ./client
    environment:
      - REACT_APP_PORT=3000
      - ENV=dev-docker

    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    command: npm start
    restart: always
